In [1]:
import json
import numpy as np
from scipy.stats import binomtest, false_discovery_control
import pandas as pd

In [2]:
#func create_paths_str(...) -> file_path

def create_paths_str(model_name, variant_name, prompt_type, dataset_type):
    return f"outputs/{model_name}/{variant_name}/responses_{prompt_type}_synthetic_dataset_{variant_name}_{dataset_type}.json"

In [3]:
#func assemble_file_paths(...) -> file_paths

def assemble_file_paths(model_name, variant_names, prompt_type):
    file_paths = []
    for dataset_type in ["gold", "random"]:
        path_list = []
        for variant in variant_names:
            path_list.append(create_paths_str(model_name, variant, prompt_type, dataset_type))
        file_paths.append(path_list)
    return file_paths

In [23]:
#func extract_output_results (file_path) -> grades

def extract_output_results(file_path):
    # Note: not secured against edge cases (like if key "init_grades" is anything else than ["[Correct]"] or ["[Incorrect]"])
    with open(file_path, 'r') as f:
        data = json.load(f)
    #print(file_path)
    length = data["stats"]["count_total"]
    grades = np.full(length, False)
    for i in range(length):
        grade = data[f"{i}"]["init_grades"][0]
        grades[i] = grade == "[Correct]"
    return grades

In [5]:
#func collect_grades (file_paths) -> grades
#   file_paths.type = list; file_paths.shape = (2, a); a = number of dataset variants
#   grades.type = np.array; grades.shape = (2, b); b = a * n; n = length of each grades list

def collect_grades(file_paths):
    grades = []
    for i in range(2):
        grades_list = []
        for j in range(len(file_paths[0])):
            grades_list.extend(extract_output_results(file_paths[i][j]))
        grades.append(grades_list)
    return np.array(grades)

In [6]:
#func calc_test_statistics (grades) -> n12, n21, n_star, z0
#   grades.type = np.array; grades.shape = (2, b)
#   n12smaller = bool (if True, the alternative hypothesis H_a is "n12 < n21". If False H_a = "n12 > n21".)

def calc_test_statistics (grades, n12smaller = True):

    grades_gold, grades_random = grades
    n12 = 0; n21 = 0
    for i in range(len(grades_gold)):
        n12 += grades_gold[i] and not grades_random[i]
        n21 += not grades_gold[i] and grades_random[i]
    n_star = n12 + n21
    z0 = (n21 - n12) / np.sqrt(n_star)  if n_star > 0 else  0
    #n_test = n21  if n12smaller else  n12   # I.e. if H_a = "n12 < n21"
    p_value = binomtest(n21, n_star, alternative='greater').pvalue  if n_star > 0 else  1
    return n12, n21, n_star, z0, p_value

In [7]:
def do_benjamini_hochberg(p_values, sig_level):
    sort_order = np.argsort(p_values)
    p_sorted = np.sort(p_values)
    count = len(p_values)
    control_line = np.linspace(sig_level, 0, count, endpoint=False)[::-1]
    rejection_boundary = np.max(np.argwhere(p_sorted <= control_line).T[0])

    rejections = np.full(count, False)
    rejections[sort_order[:rejection_boundary+1]] = True

    return rejections

In [8]:
#func run_analysis (models, prompting_types, datasets) -> results_table
#   models.type = list of strings: same with prompting_types and datasets
#   results_table = [[models], [prompting_types], [n12], [n21], [n_star], [z0], [p_value], [rejections]]

def run_analysis(models, prompting_types, datasets, bh='own', n12smaller=True):
    results_table = {
        "model":[],
        "prompting_method":[],
        "n12":[],
        "n21":[],
        "n*":[],
        "z-stat":[],
        "p-value":[],
        "reject":[],
    }
    for model in models:
        for prompt_type in prompting_types:
            file_paths = assemble_file_paths(model, datasets, prompt_type)
            grades = collect_grades(file_paths)
            n12, n21, n_star, z0, p_value = calc_test_statistics(grades, n12smaller)
            #print(p_value)

            results_table["model"].append(model)
            results_table["prompting_method"].append(prompt_type)
            results_table["n12"].append(n12)
            results_table["n21"].append(n21)
            results_table["n*"].append(n_star)
            results_table["z-stat"].append(z0)
            results_table["p-value"].append(p_value)      
    if bh == 'own' :
        results_table["reject"] = do_benjamini_hochberg(results_table["p-value"], 0.05)
    elif bh == 'scipy' :
        results_table["p-value"] = false_discovery_control(results_table["p-value"])
        results_table["reject"] = results_table["p-value"] < 0.05
    else:
        raise KeyError(f"bh == {bh} not implemented!")

    return results_table

#### Test Cases

##### Hypothesis 1

In [9]:
models = [
    "gpt-3.5-turbo",
    "gpt-4-turbo",
    "gpt-4o",
    "llama-2-70b-chat",
    "meta-llama-3-70b-instruct",
    "meta-llama-3-8b-instruct",
    "claude-3-opus-20240229",
    "claude-3-sonnet-20240229",
    "mistral-large-latest",
]
prompting_types = [
    "baseline",
    "zs_cot",
    "os",
    "os_cot",
    "fs",
    "fs_cot",
]
datasets = [
    #"linda_original",
    "linda_variant_one_to",
    "linda_variant_one_because",
    "linda_variant_one_sothat",
    "linda_variant_three",
]
results_table = run_analysis(models, prompting_types, datasets)
print(f"rejected: {results_table['reject'].sum()}/{len(results_table['reject'])}")
df = pd.DataFrame(results_table)
df.round(6)

rejected: 50/54

,model,prompting_method,n12,n21,n*,z-stat,p-value,reject
0,gpt-3.5-turbo,baseline,4,123,127,10.559542,0.000000,True
1,gpt-3.5-turbo,zs_cot,18,169,187,11.042214,0.000000,True
2,gpt-3.5-turbo,os,3,94,97,9.239650,0.000000,True
3,gpt-3.5-turbo,os_cot,16,114,130,8.595169,0.000000,True
4,gpt-3.5-turbo,fs,11,103,114,8.616589,0.000000,True
5,gpt-3.5-turbo,fs_cot,6,140,146,11.089919,0.000000,True
6,gpt-4-turbo,baseline,7,273,280,15.896541,0.000000,True
7,gpt-4-turbo,zs_cot,6,250,256,15.250000,0.000000,True
8,gpt-4-turbo,os,0,53,53,7.280110,0.000000,True
9,gpt-4-turbo,os_cot,1,72,73,8.309921,0.000000,True
10,gpt-4-turbo,fs,1,26,27,4.811252,0.000000,True
11,gpt-4-turbo,fs_cot,0,35,35,5.916080,0.000000,True
12,gpt-4o,baseline,5,269,274,15.948823,0.000000,True
13,gpt-4o,zs_cot,3,207,210,14.077337,0.000000,True
14,gpt-4o,os,0,28,28,5.291503,0.000000,True
15,gpt-4o,os_cot,7,69,76,7.111888,0.000000,True
16,gpt-4o,fs,0,1,1,1.000000,0.500000,False
17,gpt-4o,fs_cot,2,51,53,6.730668,0.000000,True
18,llama-2-70b-chat,baseline,3,156,159,12.133689,0.000000,True
19,llama-2-70b-chat,zs_cot,22,156,178,10.043725,0.000000,True
20,llama-2-70b-chat,os,43,75,118,2.945839,0.002062,True
21,llama-2-70b-chat,os_cot,34,119,153,6.871843,0.000000,True
22,llama-2-70b-chat,fs,75,85,160,0.790569,0.238441,False
23,llama-2-70b-chat,fs_cot,36,111,147,6.185896,0.000000,True
24,meta-llama-3-70b-instruct,baseline,8,244,252,14.866603,0.000000,True
25,meta-llama-3-70b-instruct,zs_cot,12,224,236,13.800025,0.000000,True
26,meta-llama-3-70b-instruct,os,20,27,47,1.021055,0.190847,False
27,meta-llama-3-70b-instruct,os_cot,18,44,62,3.302003,0.000650,True
28,meta-llama-3-70b-instruct,fs,15,23,38,1.297771,0.127938,False
29,meta-llama-3-70b-instruct,fs_cot,15,35,50,2.828427,0.003300,True
30,meta-llama-3-8b-instruct,baseline,8,200,208,13.312805,0.000000,True
31,meta-llama-3-8b-instruct,zs_cot,5,199,204,13.582717,0.000000,True
32,meta-llama-3-8b-instruct,os,10,89,99,7.939799,0.000000,True
33,meta-llama-3-8b-instruct,os_cot,17,122,139,8.905984,0.000000,True
34,meta-llama-3-8b-instruct,fs,22,69,91,4.926939,0.000000,True
35,meta-llama-3-8b-instruct,fs_cot,16,92,108,7.313103,0.000000,True
36,claude-3-opus-20240229,baseline,16,175,191,11.504836,0.000000,True
37,claude-3-opus-20240229,zs_cot,10,162,172,11.589891,0.000000,True
38,claude-3-opus-20240229,os,14,104,118,8.285172,0.000000,True
39,claude-3-opus-20240229,os_cot,12,119,131,9.348633,0.000000,True
40,claude-3-opus-20240229,fs,9,112,121,9.363636,0.000000,True
41,claude-3-opus-20240229,fs_cot,13,109,122,8.691432,0.000000,True
42,claude-3-sonnet-20240229,baseline,8,279,287,15.996624,0.000000,True
43,claude-3-sonnet-20240229,zs_cot,7,238,245,14.758049,0.000000,True
44,claude-3-sonnet-20240229,os,0,188,188,13.711309,0.000000,True
45,claude-3-sonnet-20240229,os_cot,8,127,135,10.241889,0.000000,True
46,claude-3-sonnet-20240229,fs,3,132,135,11.102552,0.000000,True
47,claude-3-sonnet-20240229,fs_cot,20,115,135,8.176298,0.000000,True
48,mistral-large-latest,baseline,8,296,304,16.517933,0.000000,True
49,mistral-large-latest,zs_cot,5,295,300,16.743158,0.000000,True
50,mistral-large-latest,os,3,73,76,8.029551,0.000000,True
51,mistral-large-latest,os_cot,4,63,67,7.207997,0.000000,True
52,mistral-large-latest,fs,5,64,69,7.102765,0.000000,True
53,mistral-large-latest,fs_cot,5,65,70,7.171372,0.000000,True

##### Hypothesis 2

In [10]:
models = [
    "gpt-3.5-turbo",
    "gpt-4-turbo",
    "gpt-4o",
    "llama-2-70b-chat",
    "meta-llama-3-70b-instruct",
    "meta-llama-3-8b-instruct",
    "claude-3-opus-20240229",
    "claude-3-sonnet-20240229",
    "mistral-large-latest",
]
prompting_types = [
    "os_bob",
    "os_bob_cot"
]
datasets = [
    #"linda_original",
    "linda_variant_one_to",
    "linda_variant_one_because",
    "linda_variant_one_sothat",
    "linda_variant_three",
    "linda_variant_four",
]
results_table = run_analysis(models, prompting_types, datasets, n12smaller=True)
print(f"rejected: {results_table['reject'].sum()}/{len(results_table['reject'])}")
df = pd.DataFrame(results_table)
df.round(6)

rejected: 18/18

,model,prompting_method,n12,n21,n*,z-stat,p-value,reject
0,gpt-3.5-turbo,os_bob,16,194,210,12.283167,0.000000,True
1,gpt-3.5-turbo,os_bob_cot,21,170,191,10.781262,0.000000,True
2,gpt-4-turbo,os_bob,2,128,130,11.050931,0.000000,True
3,gpt-4-turbo,os_bob_cot,4,145,149,11.551170,0.000000,True
4,gpt-4o,os_bob,0,20,20,4.472136,0.000001,True
5,gpt-4o,os_bob_cot,6,101,107,9.183997,0.000000,True
6,llama-2-70b-chat,os_bob,18,178,196,11.428571,0.000000,True
7,llama-2-70b-chat,os_bob_cot,24,204,228,11.920791,0.000000,True
8,meta-llama-3-70b-instruct,os_bob,14,161,175,11.112156,0.000000,True
9,meta-llama-3-70b-instruct,os_bob_cot,22,170,192,10.680980,0.000000,True
10,meta-llama-3-8b-instruct,os_bob,14,219,233,13.429997,0.000000,True
11,meta-llama-3-8b-instruct,os_bob_cot,30,204,234,11.374736,0.000000,True
12,claude-3-opus-20240229,os_bob,7,212,219,13.852616,0.000000,True
13,claude-3-opus-20240229,os_bob_cot,19,209,228,12.583057,0.000000,True
14,claude-3-sonnet-20240229,os_bob,5,275,280,16.135586,0.000000,True
15,claude-3-sonnet-20240229,os_bob_cot,19,217,236,12.888702,0.000000,True
16,mistral-large-latest,os_bob,0,212,212,14.560220,0.000000,True
17,mistral-large-latest,os_bob_cot,6,201,207,13.553437,0.000000,True

##### Hypothesis 3

In [11]:
models = [
    "gpt-3.5-turbo",
    "gpt-4-turbo",
    "gpt-4o",
    "llama-2-70b-chat",
    "meta-llama-3-70b-instruct",
    "meta-llama-3-8b-instruct",
    "claude-3-opus-20240229",
    "claude-3-sonnet-20240229",
    "mistral-large-latest",
]
prompting_types = [
    "baseline",
    "zs_cot",
    "os",
    "os_cot",
    "fs",
    "fs_cot",
]
datasets = [
    "linda_variant_four",
]
results_table = run_analysis(models, prompting_types, datasets)
print(f"rejected: {results_table['reject'].sum()}/{len(results_table['reject'])}")
df = pd.DataFrame(results_table)
df.round(6)

rejected: 19/54

,model,prompting_method,n12,n21,n*,z-stat,p-value,reject
0,gpt-3.5-turbo,baseline,9,19,28,1.889822,0.043579,False
1,gpt-3.5-turbo,zs_cot,14,23,37,1.479591,0.093871,False
2,gpt-3.5-turbo,os,7,11,18,0.942809,0.240341,False
3,gpt-3.5-turbo,os_cot,12,13,25,0.200000,0.500000,False
4,gpt-3.5-turbo,fs,3,17,20,3.130495,0.001288,True
5,gpt-3.5-turbo,fs_cot,12,20,32,1.414214,0.107664,False
6,gpt-4-turbo,baseline,5,21,26,3.137858,0.001247,True
7,gpt-4-turbo,zs_cot,1,19,20,4.024922,0.000020,True
8,gpt-4-turbo,os,0,6,6,2.449490,0.015625,True
9,gpt-4-turbo,os_cot,1,5,6,1.632993,0.109375,False
10,gpt-4-turbo,fs,2,8,10,1.897367,0.054688,False
11,gpt-4-turbo,fs_cot,3,7,10,1.264911,0.171875,False
12,gpt-4o,baseline,3,19,22,3.411211,0.000428,True
13,gpt-4o,zs_cot,1,7,8,2.121320,0.035156,False
14,gpt-4o,os,0,1,1,1.000000,0.500000,False
15,gpt-4o,os_cot,2,2,4,0.000000,0.687500,False
16,gpt-4o,fs,0,0,0,0.000000,1.000000,False
17,gpt-4o,fs_cot,2,4,6,0.816497,0.343750,False
18,llama-2-70b-chat,baseline,7,6,13,-0.277350,0.709473,False
19,llama-2-70b-chat,zs_cot,10,14,24,0.816497,0.270628,False
20,llama-2-70b-chat,os,3,17,20,3.130495,0.001288,True
21,llama-2-70b-chat,os_cot,9,20,29,2.042649,0.030714,False
22,llama-2-70b-chat,fs,8,16,24,1.632993,0.075795,False
23,llama-2-70b-chat,fs_cot,12,11,23,-0.208514,0.661180,False
24,meta-llama-3-70b-instruct,baseline,4,20,24,3.265986,0.000772,True
25,meta-llama-3-70b-instruct,zs_cot,3,27,30,4.381780,0.000004,True
26,meta-llama-3-70b-instruct,os,3,6,9,1.000000,0.253906,False
27,meta-llama-3-70b-instruct,os_cot,5,4,9,-0.333333,0.746094,False
28,meta-llama-3-70b-instruct,fs,6,6,12,0.000000,0.612793,False
29,meta-llama-3-70b-instruct,fs_cot,8,9,17,0.242536,0.500000,False
30,meta-llama-3-8b-instruct,baseline,4,18,22,2.984810,0.002172,True
31,meta-llama-3-8b-instruct,zs_cot,9,25,34,2.743977,0.004521,True
32,meta-llama-3-8b-instruct,os,1,2,3,0.577350,0.500000,False
33,meta-llama-3-8b-instruct,os_cot,9,19,28,1.889822,0.043579,False
34,meta-llama-3-8b-instruct,fs,4,6,10,0.632456,0.376953,False
35,meta-llama-3-8b-instruct,fs_cot,13,13,26,0.000000,0.577491,False
36,claude-3-opus-20240229,baseline,6,24,30,3.286335,0.000715,True
37,claude-3-opus-20240229,zs_cot,7,28,35,3.549648,0.000254,True
38,claude-3-opus-20240229,os,1,7,8,2.121320,0.035156,False
39,claude-3-opus-20240229,os_cot,4,7,11,0.904534,0.274414,False
40,claude-3-opus-20240229,fs,5,12,17,1.697749,0.071732,False
41,claude-3-opus-20240229,fs_cot,7,17,24,2.041241,0.031957,False
42,claude-3-sonnet-20240229,baseline,4,33,37,4.767571,0.000001,True
43,claude-3-sonnet-20240229,zs_cot,11,25,36,2.333333,0.014408,True
44,claude-3-sonnet-20240229,os,1,9,10,2.529822,0.010742,True
45,claude-3-sonnet-20240229,os_cot,5,10,15,1.290994,0.150879,False
46,claude-3-sonnet-20240229,fs,6,17,23,2.293659,0.017345,True
47,claude-3-sonnet-20240229,fs_cot,7,13,20,1.341641,0.131588,False
48,mistral-large-latest,baseline,3,22,25,3.800000,0.000078,True
49,mistral-large-latest,zs_cot,2,25,27,4.426352,0.000003,True
50,mistral-large-latest,os,0,3,3,1.732051,0.125000,False
51,mistral-large-latest,os_cot,0,4,4,2.000000,0.062500,False
52,mistral-large-latest,fs,2,12,14,2.672612,0.006470,True
53,mistral-large-latest,fs_cot,5,11,16,1.500000,0.105057,False

##### Hypothesis 4

In [12]:
models = [
    "gpt-3.5-turbo",
    "gpt-4-turbo",
    "gpt-4o",
    "llama-2-70b-chat",
    #"meta-llama-3-70b-instruct",
    "meta-llama-3-8b-instruct",
    "claude-3-opus-20240229",
    "claude-3-sonnet-20240229",
    "mistral-large-latest",
]
prompting_types = [
    "baseline",
    "zs_cot",
    "os",
    "os_cot",
    "fs",
    "fs_cot",
]
datasets = [
    "sets_original",
]
results_table = run_analysis(models, prompting_types, datasets)
print(f"rejected: {results_table['reject'].sum()}/{len(results_table['reject'])}")
df = pd.DataFrame(results_table)
df.round(6)

rejected: 4/48

,model,prompting_method,n12,n21,n*,z-stat,p-value,reject
0,gpt-3.5-turbo,baseline,49,1,50,-6.788225,1.000000,False
1,gpt-3.5-turbo,zs_cot,46,7,53,-5.357062,1.000000,False
2,gpt-3.5-turbo,os,7,3,10,-1.264911,0.945312,False
3,gpt-3.5-turbo,os_cot,28,28,56,0.000000,0.553073,False
4,gpt-3.5-turbo,fs,4,1,5,-1.341641,0.968750,False
5,gpt-3.5-turbo,fs_cot,13,25,38,1.946657,0.036476,False
6,gpt-4-turbo,baseline,56,0,56,-7.483315,1.000000,False
7,gpt-4-turbo,zs_cot,97,3,100,-9.400000,1.000000,False
8,gpt-4-turbo,os,49,0,49,-7.000000,1.000000,False
9,gpt-4-turbo,os_cot,47,2,49,-6.428571,1.000000,False
10,gpt-4-turbo,fs,26,9,35,-2.873524,0.999061,False
11,gpt-4-turbo,fs_cot,27,5,32,-3.889087,0.999990,False
12,gpt-4o,baseline,43,10,53,-4.532899,0.999999,False
13,gpt-4o,zs_cot,59,7,66,-6.400758,1.000000,False
14,gpt-4o,os,23,13,36,-1.666667,0.967377,False
15,gpt-4o,os_cot,11,4,15,-1.807392,0.982422,False
16,gpt-4o,fs,20,1,21,-4.146140,1.000000,False
17,gpt-4o,fs_cot,29,4,33,-4.351941,0.999999,False
18,llama-2-70b-chat,baseline,0,0,0,0.000000,1.000000,False
19,llama-2-70b-chat,zs_cot,0,0,0,0.000000,1.000000,False
20,llama-2-70b-chat,os,23,4,27,-3.656552,0.999975,False
21,llama-2-70b-chat,os_cot,29,9,38,-3.244428,0.999764,False
22,llama-2-70b-chat,fs,57,12,69,-5.417363,1.000000,False
23,llama-2-70b-chat,fs_cot,0,0,0,0.000000,1.000000,False
24,meta-llama-3-8b-instruct,baseline,0,9,9,3.000000,0.001953,True
25,meta-llama-3-8b-instruct,zs_cot,2,1,3,-0.577350,0.875000,False
26,meta-llama-3-8b-instruct,os,1,9,10,2.529822,0.010742,False
27,meta-llama-3-8b-instruct,os_cot,12,33,45,3.130495,0.001229,True
28,meta-llama-3-8b-instruct,fs,0,0,0,0.000000,1.000000,False
29,meta-llama-3-8b-instruct,fs_cot,0,0,0,0.000000,1.000000,False
30,claude-3-opus-20240229,baseline,72,9,81,-7.000000,1.000000,False
31,claude-3-opus-20240229,zs_cot,81,10,91,-7.442822,1.000000,False
32,claude-3-opus-20240229,os,62,2,64,-7.500000,1.000000,False
33,claude-3-opus-20240229,os_cot,70,1,71,-8.188793,1.000000,False
34,claude-3-opus-20240229,fs,33,0,33,-5.744563,1.000000,False
35,claude-3-opus-20240229,fs_cot,18,3,21,-3.273268,0.999889,False
36,claude-3-sonnet-20240229,baseline,0,18,18,4.242641,0.000004,True
37,claude-3-sonnet-20240229,zs_cot,1,39,40,6.008328,0.000000,True
38,claude-3-sonnet-20240229,os,0,3,3,1.732051,0.125000,False
39,claude-3-sonnet-20240229,os_cot,5,7,12,0.577350,0.387207,False
40,claude-3-sonnet-20240229,fs,8,9,17,0.242536,0.500000,False
41,claude-3-sonnet-20240229,fs_cot,1,3,4,1.000000,0.312500,False
42,mistral-large-latest,baseline,93,2,95,-9.336403,1.000000,False
43,mistral-large-latest,zs_cot,95,2,97,-9.442719,1.000000,False
44,mistral-large-latest,os,39,3,42,-5.554921,1.000000,False
45,mistral-large-latest,os_cot,61,4,65,-7.069980,1.000000,False
46,mistral-large-latest,fs,9,2,11,-2.110579,0.994141,False
47,mistral-large-latest,fs_cot,7,0,7,-2.645751,1.000000,False

##### Hypothesis 5

In [13]:
models = [
    "gpt-3.5-turbo",
    "gpt-4-turbo",
    "gpt-4o",
    "llama-2-70b-chat",
    "meta-llama-3-70b-instruct",
    "meta-llama-3-8b-instruct",
    "claude-3-opus-20240229",
    "claude-3-sonnet-20240229",
    "mistral-large-latest",
]
prompting_types = [
    "baseline",
    "zs_cot",
    "os",
    "os_cot",
    "fs",
    "fs_cot",
]
datasets = [
    "sets_original_framing",
]
results_table = run_analysis(models, prompting_types, datasets)
print(f"rejected: {results_table['reject'].sum()}/{len(results_table['reject'])}")
df = pd.DataFrame(results_table)
df.round(6)

rejected: 32/54

,model,prompting_method,n12,n21,n*,z-stat,p-value,reject
0,gpt-3.5-turbo,baseline,20,60,80,4.472136,0.000004,True
1,gpt-3.5-turbo,zs_cot,26,61,87,3.752394,0.000112,True
2,gpt-3.5-turbo,os,16,23,39,1.120897,0.168392,False
3,gpt-3.5-turbo,os_cot,42,44,86,0.215666,0.457106,False
4,gpt-3.5-turbo,fs,22,31,53,1.236245,0.135840,False
5,gpt-3.5-turbo,fs_cot,27,27,54,0.000000,0.554038,False
6,gpt-4-turbo,baseline,30,24,54,-0.816497,0.829555,False
7,gpt-4-turbo,zs_cot,27,19,46,-1.179536,0.908038,False
8,gpt-4-turbo,os,29,38,67,1.099525,0.164216,False
9,gpt-4-turbo,os_cot,30,46,76,1.835326,0.042323,False
10,gpt-4-turbo,fs,28,47,75,2.193931,0.018477,True
11,gpt-4-turbo,fs_cot,22,47,69,3.009646,0.001772,True
12,gpt-4o,baseline,17,25,42,1.234427,0.139978,False
13,gpt-4o,zs_cot,13,25,38,1.946657,0.036476,False
14,gpt-4o,os,13,56,69,5.176592,0.000000,True
15,gpt-4o,os_cot,18,55,73,4.330522,0.000008,True
16,gpt-4o,fs,8,58,66,6.154575,0.000000,True
17,gpt-4o,fs_cot,31,38,69,0.842701,0.235184,False
18,llama-2-70b-chat,baseline,0,35,35,5.916080,0.000000,True
19,llama-2-70b-chat,zs_cot,0,22,22,4.690416,0.000000,True
20,llama-2-70b-chat,os,2,144,146,11.752004,0.000000,True
21,llama-2-70b-chat,os_cot,0,4,4,2.000000,0.062500,False
22,llama-2-70b-chat,fs,1,96,97,9.645789,0.000000,True
23,llama-2-70b-chat,fs_cot,0,4,4,2.000000,0.062500,False
24,meta-llama-3-70b-instruct,baseline,5,10,15,1.290994,0.150879,False
25,meta-llama-3-70b-instruct,zs_cot,12,29,41,2.654954,0.005754,True
26,meta-llama-3-70b-instruct,os,4,21,25,3.400000,0.000455,True
27,meta-llama-3-70b-instruct,os_cot,23,47,70,2.868549,0.002791,True
28,meta-llama-3-70b-instruct,fs,2,33,35,5.239956,0.000000,True
29,meta-llama-3-70b-instruct,fs_cot,13,7,20,-1.341641,0.942341,False
30,meta-llama-3-8b-instruct,baseline,8,32,40,3.794733,0.000091,True
31,meta-llama-3-8b-instruct,zs_cot,11,26,37,2.465985,0.010037,True
32,meta-llama-3-8b-instruct,os,5,35,40,4.743416,0.000001,True
33,meta-llama-3-8b-instruct,os_cot,5,25,30,3.651484,0.000162,True
34,meta-llama-3-8b-instruct,fs,12,30,42,2.777460,0.003958,True
35,meta-llama-3-8b-instruct,fs_cot,4,41,45,5.515634,0.000000,True
36,claude-3-opus-20240229,baseline,33,43,76,1.147079,0.150936,False
37,claude-3-opus-20240229,zs_cot,35,40,75,0.577350,0.322232,False
38,claude-3-opus-20240229,os,24,29,53,0.686803,0.291566,False
39,claude-3-opus-20240229,os_cot,25,23,48,-0.288675,0.667267,False
40,claude-3-opus-20240229,fs,18,16,34,-0.342997,0.696204,False
41,claude-3-opus-20240229,fs_cot,10,13,23,0.625543,0.338820,False
42,claude-3-sonnet-20240229,baseline,8,51,59,5.598123,0.000000,True
43,claude-3-sonnet-20240229,zs_cot,7,38,45,4.621207,0.000002,True
44,claude-3-sonnet-20240229,os,13,37,50,3.394113,0.000468,True
45,claude-3-sonnet-20240229,os_cot,8,37,45,4.323065,0.000008,True
46,claude-3-sonnet-20240229,fs,17,34,51,2.380476,0.012046,True
47,claude-3-sonnet-20240229,fs_cot,11,33,44,3.316625,0.000630,True
48,mistral-large-latest,baseline,5,15,20,2.236068,0.020695,True
49,mistral-large-latest,zs_cot,7,14,21,1.527525,0.094624,False
50,mistral-large-latest,os,10,24,34,2.400980,0.012153,True
51,mistral-large-latest,os_cot,11,36,47,3.646625,0.000173,True
52,mistral-large-latest,fs,2,13,15,2.840188,0.003693,True
53,mistral-large-latest,fs_cot,2,11,13,2.496151,0.011230,True

##### Hypothesis 6

In [24]:
models = [
    "gpt-3.5-turbo",
    "gpt-4-turbo",
    "gpt-4o",
    "llama-2-70b-chat",
    "meta-llama-3-70b-instruct",
    #"meta-llama-3-8b-instruct",
    #"claude-3-opus-20240229",
    #"claude-3-sonnet-20240229",
    #"mistral-large-latest",
]
prompting_types = [
    "weak_control_zs_cot",
    "control_zs_cot",
    "weak_control_os_cot",
    "control_os_cot",
]
datasets = [
    "linda_original",
    "linda_variant_one_to",
    "linda_variant_one_because",
    "linda_variant_one_sothat",
    "linda_variant_three",
    "linda_variant_four",
    "sets_original",
]
results_table = run_analysis(models, prompting_types, datasets, n12smaller=True)
print(f"rejected: {results_table['reject'].sum()}/{len(results_table['reject'])}")
df = pd.DataFrame(results_table)
df.round(6)

rejected: 4/20

,model,prompting_method,n12,n21,n*,z-stat,p-value,reject
0,gpt-3.5-turbo,weak_control_zs_cot,84,107,191,1.664222,0.055588,False
1,gpt-3.5-turbo,control_zs_cot,63,57,120,-0.547723,0.738505,False
2,gpt-3.5-turbo,weak_control_os_cot,76,77,153,0.080845,0.500000,False
3,gpt-3.5-turbo,control_os_cot,28,21,49,-1.000000,0.873565,False
4,gpt-4-turbo,weak_control_zs_cot,26,35,61,1.152332,0.152839,False
5,gpt-4-turbo,control_zs_cot,39,3,42,-5.554921,1.000000,False
6,gpt-4-turbo,weak_control_os_cot,26,8,34,-3.086975,0.999589,False
7,gpt-4-turbo,control_os_cot,15,1,16,-3.500000,0.999985,False
8,gpt-4o,weak_control_zs_cot,9,11,20,0.447214,0.411901,False
9,gpt-4o,control_zs_cot,8,8,16,0.000000,0.598190,False
10,gpt-4o,weak_control_os_cot,7,9,16,0.500000,0.401810,False
11,gpt-4o,control_os_cot,7,13,20,1.341641,0.131588,False
12,llama-2-70b-chat,weak_control_zs_cot,99,141,240,2.711088,0.003999,True
13,llama-2-70b-chat,control_zs_cot,84,149,233,4.258292,0.000012,True
14,llama-2-70b-chat,weak_control_os_cot,120,199,319,4.423151,0.000006,True
15,llama-2-70b-chat,control_os_cot,134,142,276,0.481543,0.336788,False
16,meta-llama-3-70b-instruct,weak_control_zs_cot,71,67,138,-0.340503,0.664733,False
17,meta-llama-3-70b-instruct,control_zs_cot,51,83,134,2.764379,0.003589,True
18,meta-llama-3-70b-instruct,weak_control_os_cot,59,68,127,0.798621,0.238961,False
19,meta-llama-3-70b-instruct,control_os_cot,52,47,99,-0.502519,0.726643,False

#### Tests

In [19]:
np.linspace(1, 0, 20, endpoint=False)[::-1] * 0.05

array([0.0025, 0.005 , 0.0075, 0.01  , 0.0125, 0.015 , 0.0175, 0.02  ,
       0.0225, 0.025 , 0.0275, 0.03  , 0.0325, 0.035 , 0.0375, 0.04  ,
       0.0425, 0.045 , 0.0475, 0.05  ])

In [20]:
random_list = np.sort(np.random.rand(20) * 0.06)
linear_list = np.linspace(0.05, 0, 20, endpoint=False)[::-1]
print(random_list)
print(linear_list)
where_bigger = np.argwhere(random_list <= linear_list).T[0]
print(where_bigger)
np.max(where_bigger)

[0.00045849 0.0043322  0.00558155 0.01441019 0.01448306 0.0180893
 0.02196842 0.02214146 0.0250113  0.02804885 0.03038087 0.0330408
 0.03390001 0.03890574 0.04451873 0.04635931 0.05174444 0.05453214
 0.05602844 0.05786526]
[0.0025 0.005  0.0075 0.01   0.0125 0.015  0.0175 0.02   0.0225 0.025
 0.0275 0.03   0.0325 0.035  0.0375 0.04   0.0425 0.045  0.0475 0.05  ]
[0 1 2]

2

#### v1
make basic analysis work

In [ ]:
import json
import numpy as np
from scipy.stats import binomtest

In [ ]:
file_1 = "outputs/claude-3-opus-20240229/linda_variant_one_to/responses_baseline_synthetic_dataset_linda_variant_one_to_gold.json"
file_2 = "outputs/claude-3-opus-20240229/linda_variant_one_to/responses_baseline_synthetic_dataset_linda_variant_one_to_random.json"

In [ ]:
#func extract_output_results (file_1, file_2) -> grades_1, grades_2

def extract_output_results(file_path):
    # Note: not secured against edge cases (like if key "init_grades" is anything else than ["[Correct]"] or ["[Incorrect]"])
    with open(file_path, 'r') as f:
        data = json.load(f)
    length = data["stats"]["count_total"]
    grades = np.full(length, False)
    for i in range(length):
        grade = data[f"{i}"]["init_grades"][0]
        grades[i] = grade == "[Correct]"
    return grades

grades_1 = extract_output_results(file_1)
grades_2 = extract_output_results(file_2)

In [ ]:
#func calc_test_statistics (grades_1, grades_2) -> n12, n21, n_star, z0

def calc_test_statistics (grades_1, grades_2):
    n12 = 0; n21 = 0
    for i in range(len(grades_1)) :
        n12 += grades_1[i] and not grades_2[i]
        n21 += not grades_1[i] and grades_2[i]
    n_star = n12 + n21
    z0 = (n21 - n12) / np.sqrt(n_star)
    p_value = binomtest(n21, n_star, alternative='greater').pvalue

    return n12, n21, n_star, z0, p_value

calc_test_statistics(grades_1, grades_2)

(1, 45, 46, 6.487446070815474, 6.679101716144942e-13)

#### v2
make analysis work with the whole set of dataset variants

In [ ]:
import json
import numpy as np
from scipy.stats import binomtest

In [ ]:
#func assemble_file_paths(...) -> file_paths
def assemble_file_paths(model_name, variant_names, prompt_type):
    file_paths = []
    for dataset_type in ["gold", "random"]:
        path_list = []
        for variant in variant_names:
            path_list.append(create_paths_str(model_name, variant, prompt_type, dataset_type))
        file_paths.append(path_list)
    return file_paths



#func create_paths_str(...) -> file_path
def create_paths_str(model_name, variant_name, prompt_type, dataset_type):
    return f"outputs/{model_name}/{variant_name}/responses_{prompt_type}_synthetic_dataset_{variant_name}_{dataset_type}.json"



model_name = "claude-3-opus-20240229"
variant_names = [
    "linda_variant_one_to",
    "linda_variant_one_because",
    "linda_variant_one_sothat",
    "linda_variant_three",
]
prompt_type = "baseline"
file_paths = assemble_file_paths(model_name, variant_names, prompt_type)
file_paths

[['outputs/claude-3-opus-20240229/linda_variant_one_to/responses_baseline_synthetic_dataset_linda_variant_one_to_gold.json',
  'outputs/claude-3-opus-20240229/linda_variant_one_because/responses_baseline_synthetic_dataset_linda_variant_one_because_gold.json',
  'outputs/claude-3-opus-20240229/linda_variant_one_sothat/responses_baseline_synthetic_dataset_linda_variant_one_sothat_gold.json',
  'outputs/claude-3-opus-20240229/linda_variant_three/responses_baseline_synthetic_dataset_linda_variant_three_gold.json'],
 ['outputs/claude-3-opus-20240229/linda_variant_one_to/responses_baseline_synthetic_dataset_linda_variant_one_to_random.json',
  'outputs/claude-3-opus-20240229/linda_variant_one_because/responses_baseline_synthetic_dataset_linda_variant_one_because_random.json',
  'outputs/claude-3-opus-20240229/linda_variant_one_sothat/responses_baseline_synthetic_dataset_linda_variant_one_sothat_random.json',
  'outputs/claude-3-opus-20240229/linda_variant_three/responses_baseline_synthetic_dataset_linda_variant_three_random.json']]

In [ ]:
#func collect_grades (file_paths) -> grades
#   file_paths.type = list; file_paths.shape = (2, a); a = number of dataset variants
#   grades.type = np.array; grades.shape = (2, b); b = a * n; n = length of each grades list
def collect_grades(file_paths):
    grades = []
    for i in range(2):
        grades_list = []
        for j in range(len(file_paths[0])):
            grades_list.extend(extract_output_results(file_paths[i][j]))
        grades.append(grades_list)
    return np.array(grades)



#func extract_output_results (file_path) -> grades
def extract_output_results(file_path):
    # Note: not secured against edge cases (like if key "init_grades" is anything else than ["[Correct]"] or ["[Incorrect]"])
    with open(file_path, 'r') as f:
        data = json.load(f)
    #print(file_path)
    length = data["stats"]["count_total"]
    grades = np.full(length, False)
    for i in range(length):
        grade = data[f"{i}"]["init_grades"][0]
        grades[i] = grade == "[Correct]"
    return grades



grades = collect_grades(file_paths)
grades.shape

(2, 400)

In [ ]:
#func calc_test_statistics (grades) -> n12, n21, n_star, z0
#   grades.type = np.array; grades.shape = (2, b)
#   n12smaller = bool (if True, the alternative hypothesis H_a is "n12 < n21". If False H_a = "n12 > n21".)

def calc_test_statistics (grades, n12smaller = True):

    grades_gold, grades_random = grades
    n12 = 0; n21 = 0
    for i in range(len(grades_gold)):
        n12 += grades_gold[i] and not grades_random[i]
        n21 += not grades_gold[i] and grades_random[i]
    n_star = n12 + n21
    z0 = (n21 - n12) / np.sqrt(n_star)  if n_star > 0 else  0
    #n_test = n21  if n12smaller else  n12   # I.e. if H_a = "n12 < n21"
    p_value = binomtest(n21, n_star, alternative='greater').pvalue  if n_star > 0 else  1
    return n12, n21, n_star, z0, p_value



calc_test_statistics(grades)

(16, 175, 191, 11.504836224149503, 2.7525638867682486e-35)

#### v3
make the analysis work with all models and prompting methods

In [ ]:
import json
import numpy as np
from scipy.stats import binomtest

In [ ]:
#func run_analysis (models, prompting_types, datasets) -> results_table
#   models.type = list of strings: same with prompting_types and datasets
#   results_table = [[models], [prompting_types], [n12], [n21], [n_star], [z0], [p_value], [rejections]]

def run_analysis(models, prompting_types, datasets):
    results_table = [[], [], [], [], [], [], [], [], []]
    for model in models:
        for prompt_type in prompting_types:
            file_paths = assemble_file_paths(model, datasets, prompt_type)
            grades = collect_grades(file_paths)
            n12, n21, n_star, z0, p_value = calc_test_statistics(grades)

            results_table[0].append(model)
            results_table[1].append(prompt_type)
            results_table[2].append(n12)
            results_table[3].append(n21)
            results_table[4].append(n_star)
            results_table[5].append(z0)
            results_table[6].append(p_value)
            

    # rejections
    #results_table[7].extend(np.full(len(results_table[0]), False))
    results_table[7] = do_benjamini_hochberg(results_table[6], 0.05)

    return results_table



def do_benjamini_hochberg(p_values, sig_level):
    sort_order = np.argsort(p_values)
    p_sorted = np.sort(p_values)
    count = len(p_values)
    control_line = np.linspace(sig_level, 0, count, endpoint=False)[::-1]
    rejection_boundary = np.max(np.argwhere(p_sorted <= control_line).T[0])

    rejections = np.full(count, False)
    rejections[sort_order[:rejection_boundary+1]] = True

    return rejections
    


models = [
    "gpt-3.5-turbo",
    "gpt-4-turbo",
    "gpt-4o",
    "meta-llama-3-70b-instruct",
    "meta-llama-3-8b-instruct",
    "llama-2-70b-chat",
    "claude-3-opus-20240229",
    "claude-3-sonnet-20240229",
    "mistral-large-latest",
]
prompting_types = [
    "baseline",
    "zs_cot",
    "os",
    "os_cot",
    "fs",
    "fs_cot",
]
datasets = [
    "linda_variant_one_to",
    "linda_variant_one_because",
    "linda_variant_one_sothat",
    "linda_variant_three",
]
results_table = run_analysis(models, prompting_types, datasets)
print(results_table[7])

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True  True  True False  True False  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]

In [ ]:
models = [
    "gpt-3.5-turbo",
    "gpt-4-turbo",
    "gpt-4o",
    "meta-llama-3-70b-instruct",
    "meta-llama-3-8b-instruct",
    "llama-2-70b-chat",
    "claude-3-opus-20240229",
    "claude-3-sonnet-20240229",
    "mistral-large-latest",
]
prompting_types = [
    "baseline",
    "zs_cot",
    "os",
    "os_cot",
    "fs",
    "fs_cot",
]
datasets = [
    "linda_variant_four",
]
results_table = run_analysis(models, prompting_types, datasets)
print(np.array(results_table[2:5]).T)

[[ 9 19 28]
 [14 23 37]
 [ 7 11 18]
 [12 13 25]
 [ 3 17 20]
 [12 20 32]
 [ 5 21 26]
 [ 1 19 20]
 [ 0  6  6]
 [ 1  5  6]
 [ 2  8 10]
 [ 3  7 10]
 [ 3 19 22]
 [ 1  7  8]
 [ 0  1  1]
 [ 2  2  4]
 [ 0  0  0]
 [ 2  4  6]
 [ 4 20 24]
 [ 3 27 30]
 [ 3  6  9]
 [ 5  4  9]
 [ 6  6 12]
 [ 8  9 17]
 [ 4 18 22]
 [ 9 25 34]
 [ 1  2  3]
 [ 9 19 28]
 [ 4  6 10]
 [13 13 26]
 [ 7  6 13]
 [10 14 24]
 [ 3 17 20]
 [ 9 20 29]
 [ 8 16 24]
 [12 11 23]
 [ 6 24 30]
 [ 7 28 35]
 [ 1  7  8]
 [ 4  7 11]
 [ 5 12 17]
 [ 7 17 24]
 [ 4 33 37]
 [11 25 36]
 [ 1  9 10]
 [ 5 10 15]
 [ 6 17 23]
 [ 7 13 20]
 [ 3 22 25]
 [ 2 25 27]
 [ 0  3  3]
 [ 0  4  4]
 [ 2 12 14]
 [ 5 11 16]]

In [ ]:
import pandas as pd

#### v4

In [ ]:
import json
import numpy as np
from scipy.stats import binomtest, false_discovery_control
import pandas as pd

In [ ]:
#func run_analysis (models, prompting_types, datasets) -> results_table
#   models.type = list of strings: same with prompting_types and datasets
#   results_table = [[models], [prompting_types], [n12], [n21], [n_star], [z0], [p_value], [rejections]]

def run_analysis(models, prompting_types, datasets, bh='own', n12smaller=True):
    results_table = {
        "model":[],
        "prompting_method":[],
        "n12":[],
        "n21":[],
        "n*":[],
        "z-stat":[],
        "p-value":[],
        "reject":[],
    }
    for model in models:
        for prompt_type in prompting_types:
            file_paths = assemble_file_paths(model, datasets, prompt_type)
            grades = collect_grades(file_paths)
            n12, n21, n_star, z0, p_value = calc_test_statistics(grades, n12smaller)
            #print(p_value)

            results_table["model"].append(model)
            results_table["prompting_method"].append(prompt_type)
            results_table["n12"].append(n12)
            results_table["n21"].append(n21)
            results_table["n*"].append(n_star)
            results_table["z-stat"].append(z0)
            results_table["p-value"].append(p_value)      
    if bh == 'own' :
        results_table["reject"] = do_benjamini_hochberg(results_table["p-value"], 0.05)
    elif bh == 'scipy' :
        results_table["p-value"] = false_discovery_control(results_table["p-value"])
        results_table["reject"] = results_table["p-value"] < 0.05
    else:
        raise KeyError(f"bh == {bh} not implemented!")

    return results_table



def do_benjamini_hochberg(p_values, sig_level):
    sort_order = np.argsort(p_values)
    p_sorted = np.sort(p_values)
    count = len(p_values)
    control_line = np.linspace(sig_level, 0, count, endpoint=False)[::-1]
    rejection_boundary = np.max(np.argwhere(p_sorted <= control_line).T[0])

    rejections = np.full(count, False)
    rejections[sort_order[:rejection_boundary+1]] = True

    return rejections